spring.redis:
    host: localhost
    port: 6379
my-key: my-value2

spring:
    devtools:
        restart:
            exclude: static/**,public/**
#weather:
#    query:
#        url: http://www.weather.com.cn/data/sk/
